# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: X Days of Javalin
author:
  name: Tareq Kirresh
  url: https://tareqkirresh.com
  email: kirreshtareq@gmail.com
email: kirreshtareq@gmail.com
description: X Days of Javalin is a fullstack course for java developers to learn how to effectively and quickly create fullstack web apps
tagline: The micro-course for the micro-framework
baseurl: "/x-days-of-javalin" # the subpath of your site, e.g. /blog
url: "https://tareqkirresh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TareqK
github_username:  TareqK
search_enabled: true


# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github_repo_tree_root: https://github.com/TareqK/x-days-of-javalin/tree/master